# Generated by Django 5.1.3 on 2025-01-18 16:01

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(db_column='nombre', max_length=30, primary_key=True, serialize=False, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(db_column='direccion', max_length=255, verbose_name='Direccion')),
                ('pais', models.CharField(db_column='pais', max_length=255, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(db_column='id', max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(db_column='imagen', upload_to='productos/', verbose_name='Imagen de Producto')),
                ('descripcion', models.TextField(db_column='descripcion', verbose_name='Descripcion')),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='get_Empresa_Productos', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Producto_Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(db_column='stock', verbose_name='Stock')),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='get_Empresa_Listing', to='core.empresa', verbose_name='Empresa')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='get_Producto_Ofertas', to='core.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'Producto_Listing',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dni', models.CharField(db_column='dni', max_length=9, unique=True, verbose_name='DNI')),
                ('correo', models.EmailField(db_column='correo', max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('imagen_perfil', models.ImageField(blank=True, db_column='imagen_perfil', default='core/perfil_predeterminado.jpg', null=True, upload_to='usuarios/', verbose_name='Imagen de Perfil')),
                ('is_empresa', models.BooleanField(db_column='is_empresa', default=False, verbose_name='Quiere registrarse como empresa?')),
                ('empresa_id', models.ForeignKey(blank=True, db_column='empresa_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_Empresa_Usuarios', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'Profile',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(db_column='unidades', verbose_name='Unidades')),
                ('estado_venta', models.BooleanField(db_column='estado_venta', default=False, verbose_name='Estado')),
                ('producto_listing_id', models.ForeignKey(db_column='producto_listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='get_ProductoListing_CarritoDetalles', to='core.producto_listing', verbose_name='Oferta')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='get_Usuario_Carritos', to='core.profile', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Detalle Carrito',
                'verbose_name_plural': 'Detalle Carrito',
                'db_table': 'Carrito_Detalle',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=30, verbose_name='Nombre')),
                ('categoria_id', models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='get_Categoria_SubCategoria', to='core.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'SubCategoria',
                'verbose_name_plural': 'SubCategorias',
                'db_table': 'SubCategoria',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subCategoria_id',
            field=models.ForeignKey(db_column='subCategoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='get_SubCategoria_Productos', to='core.subcategoria', verbose_name='SubCategoria'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('carrito_detalle_id', models.ManyToManyField(db_column='carrito_detalle_id', related_name='get_Usuario_Factura', to='core.carrito_detalle', verbose_name='Detalle Carrito')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='get_Usuario_Factura', to='core.profile', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
            },
        ),
    ]
